[build-system]
requires = [
	"setuptools>=69",
	"wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "progress-reporters"
version = "0.3.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [{ name = "snowflake36u" }]
keywords = ["progress", "reporter", "tqdm", "monitoring", "task-status"]
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Topic :: Software Development :: Libraries",
	"Topic :: Software Development :: Quality Assurance",
]
dependencies = [

]

[project.optional-dependencies]
dev = [
	"build>=1.2.0",
	"pytest>=8.0",
	"tqdm>=4.66.0",
]

[project.urls]
Homepage = "https://github.com/snowflake36u/progress-reporters"
Repository = "https://github.com/snowflake36u/progress-reporters"
Issues = "https://github.com/snowflake36u/progress-reporters/issues"
Documentation = "https://github.com/snowflake36u/progress-reporters#readme"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.semantic_release]
version_variables = [
	"src/progress_reporters/__init__.py:__version__", # __main__.py内のバージョン変数を更新
]
version_toml = [
	"pyproject.toml:project.version", # pyproject.toml内のバージョンを更新
]
branch = "main"                             # 対象ブランチ
build_command = ""
allow_zero_version = true
major_on_zero = false
